config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :thanhviens do
    resources :diachis
    resources :dongiaohangs

    resources :giohangs do
      resources :chitietgiohangs
    end
    resource :bosuutaps do
      resources :chitietbosutaps
    end
  end

  resources :monans do
    resources :danhgias
  end
   
  resources :loai


  match 'auth/:provider/facebook', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get '/dangnhap', to: 'sessions#new'
  post '/dangnhap', to: 'sessions#create'
  delete '/dangxuat', to: 'sessions#destroy'

  get '/lienhe', to: 'welcome#lienhe'
  get '/gioithieu', to: 'welcome#gioithieu'
  get '/home', to: "monans#index"
  get '/thanhvien/edit' , to: 'welcome#user'

  root "monans#index"
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
    belongs_to :monan
    belongs_to :thanhvien

    validates :noidung, presence: true, length: { minimum: 20 }
end

app/models/bosuutap.rb
class Bosuutap < ApplicationRecord
    belongs_to :thanhvien
    
    has_many :chitietbosuutaps

    validates :ten, presence: true
end

app/models/chitiet.rb
class Chitiet < ApplicationRecord
    belongs_to :dongiaohang

    validates :soluong, presence: true
    validates :tenmonan, presence: true
    validates :dongia, presence: true
    validates :tongtien, presence: true
end

app/models/chitietbosuutap.rb
class Chitietbosuutap < ApplicationRecord
    belongs_to :monan
    belongs_to :bosuutap
end

app/models/chitietgiohang.rb
class Chitietgiohang < ApplicationRecord
    belongs_to :giohang
    belongs_to :thanhvien
end

app/models/diachi.rb
class Diachi < ApplicationRecord
    belongs_to :thanhvien

    validate :sonha, presence: true
    validate :duong, presence: true
    validate :phuong, presence: true
    validate :quan, presence: true
    validate :thanhpho, presence: true
end

app/models/dondathang.rb
class Dondathang < ApplicationRecord
    belongs_to :thanhvien
    belongs_to :diachi

    has_many :dongiaohangs

    validates :tongtien, presence: true
    validates :hoten, presence: true
    validates :diachi, presence: true
    validates :sdt, presence: true
end

app/models/dongiaohang.rb
class Dongiaohang < ApplicationRecord
    belongs_to :dondathang

    has_many :chitiets

    validates :tongtien, presence: true
    validates :hoten, presence: true
    validates :diachi, presence: true
    validates :sdt, presence: true
end

app/models/giohang.rb
class Giohang < ApplicationRecord
    belongs_to :thanhvien

    has_many :chitietgiohangs
end

app/models/loai.rb
class Loai < ApplicationRecord
    has_many :loaimonans
end

app/models/loaimonan.rb
class Loaimonan < ApplicationRecord
    belongs_to :loai
    belongs_to :monan
end

app/models/log.rb
class Log < ApplicationRecord
    
end

app/models/monan.rb
class Monan < ApplicationRecord
    belongs_to :thanhvien

    validate :ten, presence: true
    validate :gia, presence: true
    validate :anh, presence: true
    validate :mieuta, presence: true, , length: { minimum: 50 }
end

app/models/thanhvien.rb
class Thanhvien < ApplicationRecord
    has_many :monan, dependent: :destroy
    has_many :dondathangs
    has_many :dongiaohangs
    has_many :bosuutaps
    has_many :binhluans
    has_many :diachis
    
    validates :hoten, presence: true
    validates :email, presence: true
    validates :sdt, presence: true
    validates :password, presence: true, length: { minimum: 6 }
    has_secure_password
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/thanhviens_controller.rb
class ThanhviensController < ApplicationController
    def new
        flash.clear
        @thanhvien = Thanhvien.new
    end
    
    def edit
    end
    def create
        @thanhvien = Thanhvien.new(thanhvien_params)
        if params[:thanhvien][:password] == params[:thanhvien][:confirm_password]
            if Thanhvien.find_by(email: @thanhvien.email).nil?
                if Thanhvien.find_by(sdt: @thanhvien.sdt).nil?
                    if @thanhvien.save
                        flash[:success] = 'Đăng ký thành công!'
                        log_in @thanhvien
                        redirect_to @thanhvien
                    else
                        render 'new'
                    end
                else
                    flash[:danger] = 'Số điện thoạt đã đăng ký!'
                    render 'new'
                end
            else
                flash[:danger] = 'Email đã đăng ký!'
                render 'new'
            end
        else
            flash[:danger] = 'Mật khẩu xác nhận không khớp!'
            render 'new'
        end
    end

    def show
        redirect_to root_url
        #@thanhvien = Thanhvien.find(params[:id])
        #@monans = @thanhvien.monans
    end

    def update
        @thanhvien = current_user

        if @thanhvien.update(user_params)
            redirect_to @thanhvien
        else
            render 'edit'
        end
    end

    def destroy
        current_user.destroy
        log_out

        redirect_to root_url
    end

    def thanhvien_params
         params.require(:thanhvien).permit(:hoten, :password, :email, :sdt)
    end
end

app/helpers/binhluans_helper.rb
module BinhluansHelper
end

app/helpers/diachis_helper.rb
module DiachisHelper
end

app/helpers/loais_helper.rb
module LoaisHelper
end

app/helpers/monans_helper.rb
module MonansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= Thanhvien.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/thanhviens_helper.rb
module ThanhviensHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/thanhviens/_monans.html.erb
<!-- Page Content -->

<% @monans.each do |monan| %>
    <div class="row">

        <div class="col-sm-6 col-md-6 text-center">
            <!-- Preview Image -->
            <p>
                <%= image_tag(monan.anh, class: "img-responsive center-block") if monan.anh? %>
            </p>
        </div>

        <div class="col-sm-6 col-md-6">
            <h2>
                <%= link_to monan.ten, monan_path(monan), class: 'text-foodlover' %><br>
                <small>
                    <%= monan.luotxem.to_s + " lượt xem - "%>
                    <%= monan.luotthich.to_s + " lượt mua"%>
                </small>
            </h2>

            <h3>
                <%= monan.gia %> vnđ
            </h3>

            <p>
                <%= monan.mieuta.first(150) + "..." %>
                <%= link_to 'Xem chi tiết', monan_path(monan), class: 'btn btn-default btn-xs' %>
            </p>

            <% if current_user == @thanhvien %>
                <%= link_to 'Sửa', edit_monan_path(monan), class: 'col-xs-4 col-xs-offset-1 btn btn-warning' %>
                <%= link_to 'Xóa', monan_path(monan), method: :delete, data: { confirm: 'Are you sure?' }, class: 'col-xs-4 col-xs-offset-1 btn btn-danger' %>
            <% else %>
                <%= link_to "Đặt món", "#", class: "col-xs-6 col-xs-offset-3 btn btn-lg btn-foodlover" %>
            <% end %>

        </div>

    </div>

    <hr>

<% end %>

<!-- Pager -->
<ul class="pager">
    <li class="previous">
        <a href="#">&larr; Older</a>
    </li>
    <li class="next">
        <a href="#">Newer &rarr;</a>
    </li>
</ul>

app/views/thanhviens/getmonans.html.erb
<h3 class="foodlover">
    <%= @thanhvien.hoten %>
</h3>

<!-- Profile Entries Column -->
<%= render "monans" %>
<!-- ./Profile Entries Column -->

app/views/thanhviens/new.html.erb
<div class="col-lg-8 col-lg-offset-2 panel panel-foodlover">
  
  <h3 class="foodlover", style="width: 100%;">Đăng ký</h3>

  <%= form_for(@thanhvien) do |f| %>
    
    <% if @user != nil %>
      <% if @user.errors.any? %>
      <div id="error_explanation" class="alert alert-danger alert-dismissable">
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
          </ul>
      </div>
      <% end %>
    <% end %>

    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <div class="row">
      <div class="col-xs-4">
        <a href="#" class="btn btn-lg btn-block btn-facebook" >
          Facebook
        </a>
      </div>
      <div class="col-xs-4">
        <a href="#" class="btn btn-lg btn-block btn-twitter" >
          Twitter
        </a>
      </div>
      <div class="col-xs-4">
        <a href="#" class="btn btn-lg btn-block btn-google" >
          Google+
        </a>
      </div>
    </div>

    <hr>

    <div class="form-group">
      <div class="input-group form-group">
        <span class="input-group-addon"></span>
        <%= f.text_field :hoten, class: 'form-control', placeholder: "Nhập họ và tên", required: true %>
      </div>
      
      <div class="input-group form-group">
        <span class="input-group-addon"></span>
        <%= f.email_field :email, class: 'form-control', placeholder: "Nhập email", required: true %>
      </div>

      <div class="input-group form-group">
        <span class="input-group-addon"></span>
        <%= f.text_field :sdt, class: 'form-control', placeholder: "Nhập số điện thoại", required: true %>
      </div>
      <div class="input-group form-group">
        <span class="input-group-addon"></span>
        <%= f.password_field :password, class: "form-control", placeholder: "Nhập mật khẩu", required: true %>
      </div>

      <div class="input-group form-group">
        <span class="input-group-addon"></span>
        <%= f.password_field :confirm_password, class: "form-control", placeholder: "Nhập lại mật khẩu", required: true %>
      </div>
    </div>
    
    <%= f.submit "Đăng ký", class: "btn btn-foodlover form-control"%>
  
  <% end %>

</div>