config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :thanhviens do
    resources :diachis
    resources :dongiaohangs

    resources :giohangs do
      resources :chitietgiohangs
    end
    resource :bosuutaps do
      resources :chitietbosutaps
    end
  end

  resources :monans do
    resources :danhgias
  end
   
  resources :loai


  match 'auth/:provider/facebook', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get '/dangnhap', to: 'sessions#new'
  post '/dangnhap', to: 'sessions#create'
  delete '/dangxuat', to: 'sessions#destroy'

  get '/lienhe', to: 'welcome#lienhe'
  get '/gioithieu', to: 'welcome#gioithieu'
  get '/home', to: "monans#index"
  get '/thanhvien/edit' , to: 'welcome#user'

  root "monans#index"
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
    belongs_to :monan
    belongs_to :thanhvien

    validates :noidung, presence: true, length: { minimum: 20 }
end

app/models/bosuutap.rb
class Bosuutap < ApplicationRecord
    belongs_to :thanhvien
    
    has_many :chitietbosuutaps

    validates :ten, presence: true
end

app/models/chitiet.rb
class Chitiet < ApplicationRecord
    belongs_to :dongiaohang

    validates :soluong, presence: true
    validates :tenmonan, presence: true
    validates :dongia, presence: true
    validates :tongtien, presence: true
end

app/models/chitietbosuutap.rb
class Chitietbosuutap < ApplicationRecord
    belongs_to :monan
    belongs_to :bosuutap
end

app/models/chitietgiohang.rb
class Chitietgiohang < ApplicationRecord
    belongs_to :giohang
    belongs_to :thanhvien
end

app/models/diachi.rb
class Diachi < ApplicationRecord
    belongs_to :thanhvien

    validate :sonha, presence: true
    validate :duong, presence: true
    validate :phuong, presence: true
    validate :quan, presence: true
    validate :thanhpho, presence: true
end

app/models/dondathang.rb
class Dondathang < ApplicationRecord
    belongs_to :thanhvien
    belongs_to :diachi

    has_many :dongiaohangs

    validates :tongtien, presence: true
    validates :hoten, presence: true
    validates :diachi, presence: true
    validates :sdt, presence: true
end

app/models/dongiaohang.rb
class Dongiaohang < ApplicationRecord
    belongs_to :dondathang

    has_many :chitiets

    validates :tongtien, presence: true
    validates :hoten, presence: true
    validates :diachi, presence: true
    validates :sdt, presence: true
end

app/models/giohang.rb
class Giohang < ApplicationRecord
    belongs_to :thanhvien

    has_many :chitietgiohangs
end

app/models/loai.rb
class Loai < ApplicationRecord
    has_many :loaimonans
end

app/models/loaimonan.rb
class Loaimonan < ApplicationRecord
    belongs_to :loai
    belongs_to :monan
end

app/models/log.rb
class Log < ApplicationRecord
    
end

app/models/monan.rb
class Monan < ApplicationRecord
    belongs_to :thanhvien

    validate :ten, presence: true
    validate :gia, presence: true
    validate :anh, presence: true
    validate :mieuta, presence: true, , length: { minimum: 50 }
end

app/models/thanhvien.rb
class Thanhvien < ApplicationRecord
    has_many :monan, dependent: :destroy
    has_many :dondathangs
    has_many :dongiaohangs
    has_many :bosuutaps
    has_many :binhluans
    has_many :diachis
    
    validates :hoten, presence: true
    validates :email, presence: true
    validates :sdt, presence: true
    validates :password, presence: true, length: { minimum: 6 }
    has_secure_password
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def gioithieu
    end
    def lienhe
    end
    def user   	
    end
end

app/helpers/binhluans_helper.rb
module BinhluansHelper
end

app/helpers/diachis_helper.rb
module DiachisHelper
end

app/helpers/loais_helper.rb
module LoaisHelper
end

app/helpers/monans_helper.rb
module MonansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= Thanhvien.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/gioithieu.html.erb
<div class="row">
 	<h3 class="foodlover">Giới thiệu</h3>
</div>
<div class="row">
    <div class="col-lg-6">
        <%= image_tag 'gioithieu/gioithieu1.png', class: "img-responsive" %>
    </div>
    <div class="col-lg-6 text-justify">
        <p style="font-size:19px">CHẠM ĐẾN TRÁI TIM - Chúng tôi đam mê, sáng tạo, tư duy thoát khỏi khuôn mẫu kinh doanh và làm tất cả để cung cấp những trải nghiệm mua sắm trực tuyến độc đáo cũng như truyền cảm hứng yêu thương và kết nối đến với từng khách hàng thuộc mọi lứa tuổi và lĩnh vực khác nhau.</p>
    </div>
</div>

app/views/welcome/lienhe.html.erb
<script type="text/javascript" src="http://code.google.com/apis/gears/gears_init.js"></script>

<div class="row">
 	<h3 class="foodlover">Liên hệ</h3>
</div>
<div class="row" style="padding: 0 0 10px 0;">
    <div class="col-lg-6">
        <iframe src="https://www.google.com/maps/d/embed?mid=1ulhNg4QtDQMHXrwFLE_UpTPVEGA"></iframe>
    </div>
    <div class="col-lg-6">
        <p>Nguyễn Văn Cừ, phường 2, quận 5, TP.HCM</p>
        <p>Điện thoại: (08) 123 45 678</p>
        <p>Email: info@foodlover.vn</p>
        <p>Website: www.foodlover.vn</p>
        <p>Giờ làm việc: 9:00 AM - 6:00 PM từ Thứ 2 - Thứ 6</p>
    </div>
</div>

app/views/welcome/trangchu.html.erb
<div class="row">
	<p class="foodlover"><b>Món HOT</b></p>
	<%= link_to "Xem thêm", monans_path, class: 'xemthem' %>
</div>

<!-- Page Content -->
<div class="row">

	<% @monans.each do |monan| %>
		
		<div class="col-xs-6 col-md-4 col-sm-4 portfolio-item text-center">
			<%= link_to( monan_path(monan) ) do %>
				<%= image_tag(monan.anh, class: "img-responsive center-block") if monan.anh? %>
				<b><%= monan.ten.first(20) %></b>...<br>
				<%= link_to "Đặt món", '#', class: "btn btn-lg btn-foodlover" %>
			<% end %>
		</div>

	<% end %>

</div>

<div class="row">
	<div class="nav" style="display: inline-block;">
		<ul>
			<li class="action"><a href="/thucdon/index">Ăn sáng</a></li>
			<li><a href="/thucdon/index">Ăn trưa</a></li>
			<li><a href="/thucdon/index">Ăn chiều</a></li>
			<li><a href="/thucdon/index">Ăn tối</a></li>
		</ul>
	</div>
	<%= link_to "Xem thêm", monans_path, class: 'xemthem' %>
</div>

<div class="row">

	<% @monans.each do |monan| %>
		
		<div class="col-xs-6 col-md-4 col-sm-4 portfolio-item text-center">
			<%= link_to( monan_path(monan) ) do %>
				<%= image_tag(monan.anh, class: "img-responsive center-block") if monan.anh? %>
				<b><%= monan.ten.first(20) %></b>...<br>
				<%= link_to "Đặt món", '#', class: "btn btn-lg btn-foodlover" %>
			<% end %>
		</div>

	<% end %>

</div>

app/views/welcome/user.html.erb
<span class="help-block"></span>
<div class="row">
<div class="col-sm-2"></div>
<div class="col-sm-8" style="border:1px solid #f26d7d">
<h3 style="background-color:#f26d7d">Thông tin User:</h3>
<% @currentusers = Thanhvien.all%>
<% @currentusers.each  do |f| %>
<% if f.id == session[:user_id] %>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address:</label>
    <%= f.email %>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Name:</label>
    <%= f.hoten %>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Phone Number:</label>
    <%= f.sdt %>
  </div>
   <div class="form-group">
    <label for="exampleInputPassword1">Role:</label>
    <%= f.role %>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Ngay Sinh:</label>
    <%= f.ngaysinh%>
  </div>
  <%end %>
<% end %>
</div>
<div class="col-sm-2"></div>
</div>
<span class="help-block"></span>