config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :thanhviens do
    resources :diachis
    resources :dongiaohangs

    resources :giohangs do
      resources :chitietgiohangs
    end
    resource :bosuutaps do
      resources :chitietbosutaps
    end
  end

  resources :monans do
    resources :danhgias
  end
   
  resources :loai


  match 'auth/:provider/facebook', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get '/dangnhap', to: 'sessions#new'
  post '/dangnhap', to: 'sessions#create'
  delete '/dangxuat', to: 'sessions#destroy'

  get '/lienhe', to: 'welcome#lienhe'
  get '/gioithieu', to: 'welcome#gioithieu'
  get '/home', to: "monans#index"
  get '/thanhvien/edit' , to: 'welcome#user'

  root "monans#index"
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
    belongs_to :monan
    belongs_to :thanhvien

    validates :noidung, presence: true, length: { minimum: 20 }
end

app/models/bosuutap.rb
class Bosuutap < ApplicationRecord
    belongs_to :thanhvien
    
    has_many :chitietbosuutaps

    validates :ten, presence: true
end

app/models/chitiet.rb
class Chitiet < ApplicationRecord
    belongs_to :dongiaohang

    validates :soluong, presence: true
    validates :tenmonan, presence: true
    validates :dongia, presence: true
    validates :tongtien, presence: true
end

app/models/chitietbosuutap.rb
class Chitietbosuutap < ApplicationRecord
    belongs_to :monan
    belongs_to :bosuutap
end

app/models/chitietgiohang.rb
class Chitietgiohang < ApplicationRecord
    belongs_to :giohang
    belongs_to :thanhvien
end

app/models/diachi.rb
class Diachi < ApplicationRecord
    belongs_to :thanhvien

    validate :sonha, presence: true
    validate :duong, presence: true
    validate :phuong, presence: true
    validate :quan, presence: true
    validate :thanhpho, presence: true
end

app/models/dondathang.rb
class Dondathang < ApplicationRecord
    belongs_to :thanhvien
    belongs_to :diachi

    has_many :dongiaohangs

    validates :tongtien, presence: true
    validates :hoten, presence: true
    validates :diachi, presence: true
    validates :sdt, presence: true
end

app/models/dongiaohang.rb
class Dongiaohang < ApplicationRecord
    belongs_to :dondathang

    has_many :chitiets

    validates :tongtien, presence: true
    validates :hoten, presence: true
    validates :diachi, presence: true
    validates :sdt, presence: true
end

app/models/giohang.rb
class Giohang < ApplicationRecord
    belongs_to :thanhvien

    has_many :chitietgiohangs
end

app/models/loai.rb
class Loai < ApplicationRecord
    has_many :loaimonans
end

app/models/loaimonan.rb
class Loaimonan < ApplicationRecord
    belongs_to :loai
    belongs_to :monan
end

app/models/log.rb
class Log < ApplicationRecord
    
end

app/models/monan.rb
class Monan < ApplicationRecord
    belongs_to :thanhvien

    validate :ten, presence: true
    validate :gia, presence: true
    validate :anh, presence: true
    validate :mieuta, presence: true, , length: { minimum: 50 }
end

app/models/thanhvien.rb
class Thanhvien < ApplicationRecord
    has_many :monan, dependent: :destroy
    has_many :dondathangs
    has_many :dongiaohangs
    has_many :bosuutaps
    has_many :binhluans
    has_many :diachis
    
    validates :hoten, presence: true
    validates :email, presence: true
    validates :sdt, presence: true
    validates :password, presence: true, length: { minimum: 6 }
    has_secure_password
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/helpers/diachis_helper.rb
module DiachisHelper
end

app/helpers/loais_helper.rb
module LoaisHelper
end

app/helpers/monans_helper.rb
module MonansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= Thanhvien.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<p>
    <span id="food">FOOD</span>
    <span id="lover">LOVER</span>
</p>
<p> Copyright © 2016. All rights reserved.</p>

app/views/layouts/_header.html.erb
<!-- Row -->
<div class="row">

    <div class="col-xs-8 col-sm-4 col-md-3 col-xs-offset-2 col-sm-offset-4 col-md-offset-6">
        
        <!-- Search -->
        <%= form_tag root_path, :method => 'post' do %>
            <div class="input-group">
                <%= text_field_tag :search, '', class: 'form-control' %>
                <span class="input-group-btn", style="color:black;">
                    <%= button_tag(type: "submit", class: "btn btn-default", :name => nil) do %>
                        <span class="glyphicon glyphicon-search"></span>
                    <% end %>
                </button>
            </div>
        <% end %>
        <!-- ./Search -->

    </div>

    <!-- Sign in/ Sign up -->
    <div class="col-xs-12 col-sm-4 col-md-3 text-center ">
        <% if logged_in? %>
            
            <span><%= link_to 'Đăng món', new_monan_path %></span>
            <span>|</span>
            <span class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    <%= @current_user.hoten %>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "Hồ sơ cá nhân", "thanhvien/edit" %></li>
                    <li><%= link_to "Chỉnh sửa thông tin", '#' %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Đăng xuất", dangxuat_path, method: "delete" %></li>
                </ul>
            </span>

        <% else %>
            
            <span><%= link_to "Đăng nhập", dangnhap_path %></span>
            <span>|</span>
            <span><%= link_to "Đăng ký", new_thanhvien_path %></span>
            
        <% end %>

        <span><%= image_tag 'flag_vietnam.png' %></span>
    </div>
    <!-- ./Sign in/ Sign up -->

</div>
<!-- ./Row -->

<!-- Row -->
<div class="row">
    <!-- Navigation -->
    <nav class="navbar" role="navigation">
        <ul class="class="nav navbar-nav">
            <li><a href="/home">Trang chủ</a></li>
            <li><a href="/gioithieu">Giới thiệu</a></li>
            <li><a href="/dathang">Đặt hàng</a></li>
            <li><a href="/thucdon">Thực đơn</a></li>
            <li><a href="/lienhe">Liên hệ</a></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </nav>
    <!-- ./Navigation -->
</div>
<!-- ./Row -->

<!-- Row -->
<div class="row text-center">
    <p>
        <span class="food">FOOD</span>
        <span class="lover">LOVER</span>
    </p>
</div>
<!-- Row -->

<!-- Row -->
<div class="row text-center">
    <div id="tag_line">
        IT'S A TAG LINE, WHERE YOU CAN WRITE A KEY POINT OF YOUR IDEA.
    </div>
</div>
<!-- ./Row -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food Lover</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <div id="user-widget">
    <% if current_user %>
    Welcome <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
    <% end %>
</div>
    <div class="row col-lg-12">
      <!-- Left Sidebar -->

      <!-- Content -->
      <div class="col-md-8 col-md-offset-2", role="main">
        <div class="row", style="padding-top: 10px">
          <%= yield %>
        </row>
      </div>
      <!-- Right Sidebar -->

      <footer>
        <%= render 'layouts/footer' %>
      </footer>
    </div>
  </body>
</html>